### ISSUE TITLE
Edit entity endpoints

### ISSUE THREAD

**Issue by colingoodman** [colingoodman/flaskchat#35]
Need the ability to edit attributes for users and rooms.

**Comment by colingoodman** [comment]
I am passing this to you guys to test. Observe POST to `/users/<user_id>` and let me know how things go. @heisler98 @johnchapple

**Comment by heisler98** [comment]
Food for thought... what if you changed the POST on `users/<id>` to a POST on `users/me`?

**Comment by heisler98** [comment]
If this is appropriate, would you mind handing me the changed user object as the response? Not sure whether that's standard, or correct.

**Comment by heisler98** [comment]
I have implemented user entity editing. Is there any room entity editing? I see none in the documentation. I require clarity about the PUT on the admin endpoint, if that's still in your plan. 

I receive this exception on req'ing a GET or a PUT on `room/<id>/mute`:
```Traceback (most recent call last):
  File "/tiny/flask_venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.handle_exception(e)
  File "/tiny/flask_venv/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/tiny/flask_venv/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/tiny/flask_venv/lib/python3.9/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/tiny/flask_venv/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/tiny/flask_venv/lib/python3.9/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/tiny/flask_venv/lib/python3.9/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/tiny/flask_venv/lib/python3.9/site-packages/flask_jwt_extended/view_decorators.py", line 125, in decorator
    return current_app.ensure_sync(fn)(*args, **kwargs)
  File "/tiny/flaskchat/api/rooms.py", line 150, in room_mute
    mute_status = room_is_mute(room_id, user_id)
  File "/tiny/flaskchat/db.py", line 199, in room_is_mute
    output = room_members_collection.find_one({'_id.user_id': ObjectId(user_id), '_id.room_id': ObjectId(room_id)},
  File "/tiny/flask_venv/lib/python3.9/site-packages/pymongo/collection.py", line 1318, in find_one
    cursor = self.find(filter, *args, **kwargs)
  File "/tiny/flask_venv/lib/python3.9/site-packages/pymongo/collection.py", line 1523, in find
    return Cursor(self, *args, **kwargs)
  File "/tiny/flask_venv/lib/python3.9/site-packages/pymongo/cursor.py", line 170, in __init__
    projection = helpers._fields_list_to_dict(projection, "projection")
  File "/tiny/flask_venv/lib/python3.9/site-packages/pymongo/helpers.py", line 261, in _fields_list_to_dict
    raise TypeError("%s must be a list of key names, each an "
TypeError: projection must be a list of key names, each an instance of str
```
